namespace: rhtelco
name: automation
readme: README.md
authors:
  - "Telco5G DevOps CI team"
description: Telco5G automation collection
license:
  - GPL-3.0-or-later
tags:
  - automation
  - telco
dependencies: {}
repository: https://github.com/openshift-kni/telco-ci
documentation: https://github.com/openshift-kni/telco-ci
homepage: https://github.com/openshift-kni/telco-ci
issues: https://github.com/openshift-kni/telco-ci
build_ignore:
  - "*.tar.gz"
  - build_artifact
  - test-requirements*
  - tests
  - tox.ini
  - .gitignore
  - .pytest_cache
  - .tox
  - .env
  - .vscode
  - contrib
  - changelogs
version: 0.0.1
