---
- name: Create LLC performance profile
  kubernetes.core.k8s:
    kubeconfig: "{{ pp_kubeconfig | default(omit) }}"
    state: present
    definition:
      apiVersion: performance.openshift.io/v2
      kind: PerformanceProfile
      metadata:
        name: "{{ llc_performance_profile_name }}"
        namespace: "{{ llc_performance_profile_namespace }}"
      spec:
        additionalKernelArgs:
          - module_blacklist=irdma
        cpu:
          isolated: 2-255,258-511
          reserved: 0-1,256-257
        machineConfigPoolSelector:
          machineconfiguration.openshift.io/role: worker-cnf
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - count: 1
              node: 0
              size: 1G
            - count: 128
              node: 1
              size: 2M
        net:
          userLevelNetworking: true
        nodeSelector:
          node-role.kubernetes.io/worker-cnf: ""
        numa:
          topologyPolicy: single-numa-node
        realTimeKernel:
          enabled: false
        workloadHints:
          highPowerConsumption: true
          perPodPowerManagement: false
          realTime: true

- name: Wait for performance profile to be applied
  kubernetes.core.k8s_info:
    kubeconfig: "{{ pp_kubeconfig | default(omit) }}"
    api_version: performance.openshift.io/v2
    kind: PerformanceProfile
    name: "{{ llc_performance_profile_name }}"
    namespace: "{{ llc_performance_profile_namespace }}"
  register: performance_profile_status
  until:
    - "'resources' in performance_profile_status"
    - performance_profile_status.resources | length > 0
    - performance_profile_status.resources[0].status is defined
  retries: 30
  delay: 10