---
- name: Create LLC machine config pool
  kubernetes.core.k8s:
    kubeconfig: "{{ pp_kubeconfig | default(omit) }}"
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfigPool
      labels:
        machineconfiguration.openshift.io/role: worker-cnf
      metadata:
        name: "{{ llc_mcp_name }}"
        namespace: "{{ llc_mcp_namespace | default(omit) }}"
      spec:
        machineConfigSelector:
          matchExpressions:
            - { key: machineconfiguration.openshift.io/role, operator: In, values: [worker-cnf, worker] }
        pause: false
        nodeSelector:
          matchLabels:
            node-role.kubernetes.io/worker-cnf: ""

- name: Wait for the 'worker-cnf' MachineConfigPool to be created
  kubernetes.core.k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    name: worker-cnf
    kubeconfig: "{{ pp_kubeconfig | default(omit) }}"
  register: mcp_info
  until: mcp_info.resources | default([]) | length > 0
  retries: 5
  delay: 10
  # The `changed_when` is set to false because this is a polling task and
  # should not be considered a change to the system.
  changed_when: false


- name: Create LLC performance profile
  kubernetes.core.k8s:
    kubeconfig: "{{ pp_kubeconfig | default(omit) }}"
    state: present
    definition:
      apiVersion: performance.openshift.io/v2
      kind: PerformanceProfile
      metadata:
        name: "{{ llc_performance_profile_name }}"
        namespace: "{{ llc_performance_profile_namespace }}"
      spec:
        additionalKernelArgs:
          - module_blacklist=irdma
        cpu:
          isolated: 2-255,258-511
          reserved: 0-1,256-257
        machineConfigPoolSelector:
          machineconfiguration.openshift.io/role: worker-cnf
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - count: 1
              node: 0
              size: 1G
            - count: 128
              node: 1
              size: 2M
        net:
          userLevelNetworking: true
        nodeSelector:
          node-role.kubernetes.io/worker-cnf: ""
        numa:
          topologyPolicy: single-numa-node
        realTimeKernel:
          enabled: false
        workloadHints:
          highPowerConsumption: true
          perPodPowerManagement: false
          realTime: true

- name: Wait for MachineConfigPool to initialize
  ansible.builtin.pause:
    seconds: 8

- name: Poll mcp until it starts updating
  kubernetes.core.k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    name: "{{ llc_mcp_name }}"
    kubeconfig: "{{ pp_kubeconfig | default(omit) }}"
  register: mcp_info
  until:
    - "'resources' in mcp_info"
    - mcp_info.resources | length > 0
    - mcp_info.resources[0].status is defined
    - mcp_info.resources[0].status.conditions is defined
    - mcp_info.resources[0].status.conditions | json_query("[?type=='Updating' && status=='True']") | length > 0
  retries: 5
  delay: 10

- name: Poll mcp until it is updated
  kubernetes.core.k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    name: "{{ llc_mcp_name }}"
    kubeconfig: "{{ pp_kubeconfig | default(omit) }}"
  register: mcp_updated_info
  until:
    - "'resources' in mcp_updated_info"
    - mcp_updated_info.resources | length > 0
    - mcp_updated_info.resources[0].status is defined
    - mcp_updated_info.resources[0].status.conditions is defined
    - mcp_updated_info.resources[0].status.conditions | json_query("[?type=='Updated' && status=='True']") | length > 0
  retries: 10
  delay: 30
