name: Sanity and Linters
on:
  push:
  pull_request:

jobs:
  ansible_lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "-c .ansible-lint"
          setup_python: "true"
          working_directory: ""
          requirements_file: "ansible-requirements.yaml"
